### PR TITLE
Add support for Symfony 5 and Phpunit 8

### PR DESCRIPTION
**Pull request by Sander-Toonen**
Symfony 5 got released today. Let's make this bundle compatible with that! I believe the constraints can be updated without breaking anything, also updated the README a bit to reflect the new config path that is used since Symfony 4.

### CODE REVIEW

**Comment by remmel** [comment]
@excelwebzone Hi, can you please accept that PR?

**Comment by excelwebzone** [comment]
build failed.. make sure to fix it before I merge it. Thanks.

**Comment by remmel** [comment]
Finally that PR is partly useless as Symfony 5 is now handled : https://github.com/excelwebzone/EWZRecaptchaBundle/commit/1e87dff482391892c47b858e41e4150913785927 (but not Phpunit 8)

**Comment by excelwebzone** [comment]
@Sander-Toonen Please fix the unit testing before I can merge the code. Thanks.

**Pull request closed without merging**
