### PR TITLE
Set httpGet method to protected to make it overridable

### PR DESCRIPTION
**Pull request by maximelebastard**
Hi,

I cannot use the httpGet method you provided because of my security policy that turns off "allow_url_fopen" in the php.ini.

I'd like to use CURL to make the request, but the method is private so I have almost to copy paste the whole class to override the few lines of httpGet and make it with my own http client.

I propose to make this method protected so that anyone can override it easily and use the http client they like.

### CODE REVIEW

**Comment by excelwebzone** [comment]
Let's see if other users like it.. but for now you can just create your own class and change it.. or update the PR code to use curl instead

**Comment by maximelebastard** [comment]
When I say that I use curl, indeed I'm using my own HTTP Client class that uses CURL with more features (benchmarking, logging, client certificates...). 

I think I'm not the only one to use a custom HTTP client on Symfony, and this is why I think it's better to let people make the implementation they want.

For the moment, I overrided the whole validator class and it works, but because of httpGet being private, I did a copy-paste of 110 lines for 3 lines edited. This is not really good for maintenance.

**Comment by pulzarraider** [comment]
👍 for this change. I have the same issue: overloading just the client can`t be done easily.  Changing the private method to protected will help a lot.

**Comment by mablae** [comment]
Method is private on purpose. Instead of reinventing the wheel and argue between different Http Client implementation, we should have a look at http://httplug.io/ - It's already a solved problem. Use of that lib will allow the user to use whatever client implementation she wants. (Most have guzzle installed anyways)

**Comment by mablae** [comment]
@maximelebastard Also inheritance is wrong most of the times. Better make the class final and give it an interface. Composition over inheritance!

**Comment by pulzarraider** [comment]
@excelwebzone This isssue is not solved. We want some better way how to get the content from the remote server.

**Comment by tomaszpolska** [comment]
Google Recaptcha https://github.com/google/recaptcha offers three implementations of a request method (post, curl, socket). Why did you limit to only one using file_get_contents which generates SSL issues in some environments? How I can use curl with your bundle?

**Pull request closed without merging**
