### PR TITLE
Do not validate EWZRecaptchaType when disabled

### PR DESCRIPTION
**Pull request by steevechristen**
This resolves issue #252.

### CODE REVIEW

**Comment by steevechristen** [comment]
@excelwebzone This time with passed CI tests

**Comment by steevechristen** [comment]
@excelwebzone is this good for you?

**Comment by excelwebzone** [comment]
There is no need for this PR since the validation ignore already when disabled.. see https://github.com/excelwebzone/EWZRecaptchaBundle/blob/3f347b39ebfce3d9a0d9a81328bedf1f4a6c7889/src/Validator/Constraints/IsTrueValidator.php#L85

**Comment by steevechristen** [comment]
This isn't always true, as described in #252. 

When passing the validation constraints as an option to the FormType (as described in the readme), the validation is done even if the reCAPTCHA is disabled.

**Comment by excelwebzone** [comment]
In that case just give the field a different validation group and it will ignore it. (like: `ignore-group`)

**Comment by steevechristen** [comment]
I just want it to be ignored in test environment, where I don't have public_key and private_key. If I define another validation group, it will be always ignored. 

The problem occurs since v1.5.19.

**Comment by excelwebzone** [comment]
Just remove the field from form when in debug mode.

**Comment by steevechristen** [comment]
The problem occurs in **test** environment during our acceptance tests, which are automated in our CI/CD. The tests are triggered on every release, therefor not possible to just remove the field.

This PR handles the case you define in your readme, when passing the validation constraints as an option to the FormType:
```php
        'constraints' => array(
            new RecaptchaTrue()
        )
```

This should be fixed.

**Comment by excelwebzone** [comment]
If you pass enabled = false it will automatically validate the field.. and again, if it still not working you can ether remove the field when using debug mode or change the validation group for that specific form.

```yaml
    ewz_recaptcha.validator.true:
        class: EWZ\Bundle\RecaptchaBundle\Validator\Constraints\IsTrueValidator
        public: true
        arguments:
            - '%ewz_recaptcha.enabled%'
            - '@ewz_recaptcha.recaptcha'
            - '@request_stack'
            - '%ewz_recaptcha.verify_host%'
            - '@?security.authorization_checker'
            - '%ewz_recaptcha.trusted_roles%'
        tags:
            - { name: validator.constraint_validator, alias: 'ewz_recaptcha.true' }
```

**Comment by steevechristen** [comment]
As already mentioned, this doesn't work when passing the validation constraints as an option to the FormType (as described in the readme of this repo), because the validation would then trigger a RuntimeException "No secret provided" (see #252):
```php
        'constraints' => array(
            new RecaptchaTrue()
        )
```

If someone encounters the same problem, we fixed it by replacing the public_key and the private_key by spaces
```yml
ewz_recaptcha:
    public_key: ' '
    private_key: ' '
    enabled: false
```

This prevents the RuntimException and the validate automatically (because of `enabled: false`) as explained by @excelwebzone.

**Pull request closed without merging**
